/* ============================================================
   6. CUSTOMER ADDRESS  (~65 rows: every customer gets a Permanent
      address, ~15 also get a second Current address)
   ============================================================ */
INSERT INTO CustomerAddress (CustomerID, AddressType, HouseNumber, Street, Area, Landmark, City, District, State, PostalCode, Country, AddressProofType) VALUES
(7, 'Permanent', '801', N'Airport Road', N'Phase 16', N'Near Bus Depot', N'Pune', N'Pune', N'Maharashtra', '608223', 'India', 'UtilityBill'),
(8, 'Permanent', '330', N'Temple Street', N'Phase 6', N'Near City Hospital', N'Lucknow', N'Lucknow', N'Uttar Pradesh', '434367', 'India', 'VoterID'),
(8, 'Current', '60', N'Market Road', N'Sector 17', N'Near Mall', N'Bengaluru', N'Bengaluru', N'Karnataka', '712356', 'India', 'UtilityBill'),
(9, 'Permanent', '103', N'Station Road', N'Block 8', N'Near Metro Station', N'Mumbai', N'Mumbai', N'Maharashtra', '659614', 'India', 'Aadhaar'),
(10, 'Permanent', '590', N'Temple Street', N'Phase 6', N'Near Central Park', N'New Delhi', N'New Delhi', N'Delhi', '348041', 'India', 'VoterID'),
(11, 'Permanent', '936', N'Nehru Street', N'Sector 12', N'Near Bus Depot', N'Chennai', N'Chennai', N'Tamil Nadu', '690984', 'India', 'Passport'),
(12, 'Permanent', '857', N'Market Road', N'Block 10', N'Near Central Park', N'New Delhi', N'New Delhi', N'Delhi', '614259', 'India', 'Aadhaar'),
(12, 'Current', '617', N'Station Road', N'Sector 1', N'Near Railway Station', N'New Delhi', N'New Delhi', N'Delhi', '601207', 'India', 'UtilityBill'),
(13, 'Permanent', '940', N'Nehru Street', N'Sector 5', N'Near Metro Station', N'Chennai', N'Chennai', N'Tamil Nadu', '851763', 'India', 'Passport'),
(14, 'Permanent', '61', N'MG Road', N'Sector 19', N'Near Central Park', N'Chennai', N'Chennai', N'Tamil Nadu', '216308', 'India', 'VoterID'),
(15, 'Permanent', '383', N'Airport Road', N'Block 13', N'Near Bus Depot', N'Hyderabad', N'Hyderabad', N'Telangana', '205939', 'India', 'UtilityBill'),
(16, 'Permanent', '162', N'Airport Road', N'Phase 16', N'Near Metro Station', N'Mumbai', N'Mumbai', N'Maharashtra', '282664', 'India', 'VoterID'),
(17, 'Permanent', '806', N'Lake View Road', N'Sector 19', N'Near Central Park', N'Indore', N'Indore', N'Madhya Pradesh', '496764', 'India', 'UtilityBill'),
(18, 'Permanent', '131', N'Church Street', N'Block 1', N'Near Bus Depot', N'Bengaluru', N'Bengaluru', N'Karnataka', '510623', 'India', 'VoterID'),
(18, 'Current', '326', N'Nehru Street', N'Sector 8', N'Near Railway Station', N'Indore', N'Indore', N'Madhya Pradesh', '693022', 'India', 'UtilityBill'),
(19, 'Permanent', '145', N'Lake View Road', N'Block 3', N'Near Central Park', N'Jaipur', N'Jaipur', N'Rajasthan', '463656', 'India', 'UtilityBill'),
(19, 'Current', '842', N'Airport Road', N'Sector 11', N'Near Mall', N'Hyderabad', N'Hyderabad', N'Telangana', '111949', 'India', 'Aadhaar'),
(20, 'Permanent', '256', N'Airport Road', N'Sector 12', N'Near Metro Station', N'New Delhi', N'New Delhi', N'Delhi', '213282', 'India', 'Aadhaar'),
(20, 'Current', '751', N'Temple Street', N'Sector 6', N'Near Mall', N'Ahmedabad', N'Ahmedabad', N'Gujarat', '617033', 'India', 'Aadhaar'),
(21, 'Permanent', '560', N'Temple Street', N'Sector 16', N'Near Bus Depot', N'Chennai', N'Chennai', N'Tamil Nadu', '782591', 'India', 'Passport'),
(21, 'Current', '819', N'MG Road', N'Sector 10', N'Near Tech Park', N'Hyderabad', N'Hyderabad', N'Telangana', '434198', 'India', 'Aadhaar'),
(22, 'Permanent', '76', N'Lake View Road', N'Sector 13', N'Near Central Park', N'Mumbai', N'Mumbai', N'Maharashtra', '867541', 'India', 'Aadhaar'),
(23, 'Permanent', '347', N'Nehru Street', N'Block 16', N'Near City Hospital', N'Hyderabad', N'Hyderabad', N'Telangana', '552275', 'India', 'Passport'),
(24, 'Permanent', '161', N'MG Road', N'Sector 11', N'Near Central Park', N'Kolkata', N'Kolkata', N'West Bengal', '299212', 'India', 'DrivingLicense'),
(25, 'Permanent', '272', N'College Road', N'Phase 10', N'Near Central Park', N'Kochi', N'Kochi', N'Kerala', '200575', 'India', 'Aadhaar'),
(26, 'Permanent', '861', N'Market Road', N'Sector 2', N'Near Metro Station', N'Kochi', N'Kochi', N'Kerala', '104000', 'India', 'DrivingLicense'),
(26, 'Current', '492', N'Station Road', N'Sector 4', N'Near Tech Park', N'Indore', N'Indore', N'Madhya Pradesh', '317005', 'India', 'UtilityBill'),
(27, 'Permanent', '84', N'Market Road', N'Sector 10', N'Near Government School', N'Bengaluru', N'Bengaluru', N'Karnataka', '593821', 'India', 'DrivingLicense'),
(28, 'Permanent', '94', N'College Road', N'Block 13', N'Near Central Park', N'Bengaluru', N'Bengaluru', N'Karnataka', '489043', 'India', 'DrivingLicense'),
(29, 'Permanent', '46', N'Park Avenue', N'Phase 15', N'Near Metro Station', N'Ahmedabad', N'Ahmedabad', N'Gujarat', '337232', 'India', 'UtilityBill'),
(30, 'Permanent', '771', N'Airport Road', N'Block 4', N'Near City Hospital', N'Mumbai', N'Mumbai', N'Maharashtra', '800596', 'India', 'UtilityBill'),
(31, 'Permanent', '995', N'Nehru Street', N'Sector 18', N'Near City Hospital', N'Kolkata', N'Kolkata', N'West Bengal', '505910', 'India', 'VoterID'),
(32, 'Permanent', '704', N'Market Road', N'Block 8', N'Near Government School', N'Kochi', N'Kochi', N'Kerala', '413369', 'India', 'Aadhaar'),
(33, 'Permanent', '515', N'Nehru Street', N'Block 19', N'Near Bus Depot', N'Hyderabad', N'Hyderabad', N'Telangana', '254610', 'India', 'Aadhaar'),
(34, 'Permanent', '178', N'Church Street', N'Sector 7', N'Near Central Park', N'Ahmedabad', N'Ahmedabad', N'Gujarat', '144748', 'India', 'DrivingLicense'),
(34, 'Current', '207', N'College Road', N'Sector 5', N'Near Railway Station', N'Kolkata', N'Kolkata', N'West Bengal', '370413', 'India', 'Aadhaar'),
(35, 'Permanent', '90', N'Temple Street', N'Block 13', N'Near Bus Depot', N'Hyderabad', N'Hyderabad', N'Telangana', '441968', 'India', 'UtilityBill'),
(36, 'Permanent', '806', N'Airport Road', N'Block 19', N'Near Bus Depot', N'Hyderabad', N'Hyderabad', N'Telangana', '539976', 'India', 'Aadhaar'),
(37, 'Permanent', '581', N'Nehru Street', N'Block 4', N'Near City Hospital', N'Mumbai', N'Mumbai', N'Maharashtra', '690016', 'India', 'Aadhaar'),
(38, 'Permanent', '902', N'Lake View Road', N'Phase 9', N'Near Government School', N'Kochi', N'Kochi', N'Kerala', '786594', 'India', 'DrivingLicense'),
(39, 'Permanent', '39', N'Church Street', N'Phase 13', N'Near Central Park', N'Jaipur', N'Jaipur', N'Rajasthan', '748276', 'India', 'VoterID'),
(40, 'Permanent', '40', N'Temple Street', N'Phase 8', N'Near City Hospital', N'Pune', N'Pune', N'Maharashtra', '881975', 'India', 'DrivingLicense'),
(41, 'Permanent', '21', N'Lake View Road', N'Phase 10', N'Near Metro Station', N'Chennai', N'Chennai', N'Tamil Nadu', '615500', 'India', 'Aadhaar'),
(42, 'Permanent', '138', N'Park Avenue', N'Block 15', N'Near Metro Station', N'New Delhi', N'New Delhi', N'Delhi', '382507', 'India', 'DrivingLicense'),
(43, 'Permanent', '193', N'Market Road', N'Sector 14', N'Near Government School', N'Hyderabad', N'Hyderabad', N'Telangana', '896386', 'India', 'VoterID'),
(44, 'Permanent', '528', N'Church Street', N'Sector 10', N'Near Bus Depot', N'Hyderabad', N'Hyderabad', N'Telangana', '522979', 'India', 'Passport'),
(45, 'Permanent', '901', N'Nehru Street', N'Sector 6', N'Near Central Park', N'Lucknow', N'Lucknow', N'Uttar Pradesh', '310477', 'India', 'Aadhaar'),
(45, 'Current', '52', N'Lake View Road', N'Sector 7', N'Near Mall', N'Ahmedabad', N'Ahmedabad', N'Gujarat', '486244', 'India', 'Aadhaar'),
(46, 'Permanent', '407', N'College Road', N'Sector 1', N'Near Central Park', N'Lucknow', N'Lucknow', N'Uttar Pradesh', '490559', 'India', 'DrivingLicense'),
(47, 'Permanent', '984', N'Market Road', N'Block 18', N'Near Metro Station', N'Mumbai', N'Mumbai', N'Maharashtra', '460971', 'India', 'Passport'),
(48, 'Permanent', '767', N'Airport Road', N'Sector 10', N'Near City Hospital', N'Bengaluru', N'Bengaluru', N'Karnataka', '505343', 'India', 'Aadhaar'),
(48, 'Current', '799', N'Station Road', N'Sector 8', N'Near Railway Station', N'Nagpur', N'Nagpur', N'Maharashtra', '336047', 'India', 'VoterID'),
(49, 'Permanent', '276', N'College Road', N'Phase 17', N'Near City Hospital', N'New Delhi', N'New Delhi', N'Delhi', '815338', 'India', 'Aadhaar'),
(50, 'Permanent', '663', N'Church Street', N'Block 1', N'Near Central Park', N'Mumbai', N'Mumbai', N'Maharashtra', '364650', 'India', 'VoterID'),
(51, 'Permanent', '730', N'Airport Road', N'Block 9', N'Near Government School', N'Bengaluru', N'Bengaluru', N'Karnataka', '494763', 'India', 'UtilityBill'),
(52, 'Permanent', '478', N'Park Avenue', N'Block 17', N'Near Bus Depot', N'New Delhi', N'New Delhi', N'Delhi', '516444', 'India', 'VoterID'),
(52, 'Current', '679', N'Lake View Road', N'Sector 18', N'Near Railway Station', N'Lucknow', N'Lucknow', N'Uttar Pradesh', '722615', 'India', 'VoterID'),
(53, 'Permanent', '306', N'College Road', N'Sector 16', N'Near City Hospital', N'Bengaluru', N'Bengaluru', N'Karnataka', '452618', 'India', 'UtilityBill'),
(54, 'Permanent', '268', N'College Road', N'Block 10', N'Near Central Park', N'Bengaluru', N'Bengaluru', N'Karnataka', '257212', 'India', 'VoterID'),
(55, 'Permanent', '825', N'Nehru Street', N'Phase 11', N'Near Central Park', N'Hyderabad', N'Hyderabad', N'Telangana', '856320', 'India', 'Aadhaar'),
(56, 'Permanent', '266', N'Temple Street', N'Phase 13', N'Near City Hospital', N'Bengaluru', N'Bengaluru', N'Karnataka', '711344', 'India', 'VoterID');
GO